// flow-typed signature: 9edfd0177f3d886cb2d43c2ea03252e6
// flow-typed version: <<STUB>>/ampersand-app_v2.0.0/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ampersand-app'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ampersand-app' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ampersand-app/ampersand-app' {
  declare module.exports: any;
}

declare module 'ampersand-app/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ampersand-app/ampersand-app.js' {
  declare module.exports: $Exports<'ampersand-app/ampersand-app'>;
}
declare module 'ampersand-app/test/index.js' {
  declare module.exports: $Exports<'ampersand-app/test/index'>;
}
