// flow-typed signature: 878088dcc17f70bf907295a60227d4f2
// flow-typed version: <<STUB>>/exceljs_v1.6.2/flow_v0.82.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'exceljs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'exceljs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'exceljs/dist/es5/config/set-value' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/csv/csv' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/csv/line-buffer' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/csv/stream-converter' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/doc/cell' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/doc/column' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/doc/data-validations' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/doc/defined-names' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/doc/enums' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/doc/modelcontainer' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/doc/range' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/doc/row' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/doc/workbook' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/doc/worksheet' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/exceljs.browser' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/exceljs.nodejs' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/index' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/stream/xlsx/hyperlink-reader' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/stream/xlsx/sheet-rels-writer' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/stream/xlsx/workbook-reader' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/stream/xlsx/workbook-writer' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/stream/xlsx/worksheet-reader' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/stream/xlsx/worksheet-writer' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/utils/auto-drain' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/utils/cell-matrix' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/utils/col-cache' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/utils/flow-control' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/utils/promish' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/utils/shared-formula' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/utils/shared-strings' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/utils/stream-base64' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/utils/stream-buf' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/utils/string-buf' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/utils/string-builder' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/utils/stuttered-pipe' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/utils/typed-stack' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/utils/under-dash' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/utils/utils' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/utils/xml-stream' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/utils/zip-stream' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/xlsx/defaultnumformats' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/xlsx/rel-type' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/xlsx/xform/base-xform' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/xlsx/xform/book/defined-name-xform' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/xlsx/xform/book/sheet-xform' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/xlsx/xform/book/workbook-properties-xform' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/xlsx/xform/book/workbook-view-xform' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/xlsx/xform/book/workbook-xform' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/xlsx/xform/composite-xform' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/xlsx/xform/core/app-heading-pairs-xform' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/xlsx/xform/core/app-titles-of-parts-xform' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/xlsx/xform/core/app-xform' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/xlsx/xform/core/content-types-xform' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/xlsx/xform/core/core-xform' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/xlsx/xform/core/relationship-xform' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/xlsx/xform/core/relationships-xform' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/xlsx/xform/drawing/blip-fill-xform' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/xlsx/xform/drawing/blip-xform' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/xlsx/xform/drawing/cell-position-xform' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/xlsx/xform/drawing/drawing-xform' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/xlsx/xform/drawing/nv-pic-pr-xform' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/xlsx/xform/drawing/pic-xform' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/xlsx/xform/drawing/sp-pr' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/xlsx/xform/drawing/two-cell-anchor-xform' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/xlsx/xform/list-xform' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/xlsx/xform/sheet/auto-filter-xform' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/xlsx/xform/sheet/cell-xform' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/xlsx/xform/sheet/col-xform' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/xlsx/xform/sheet/data-validations-xform' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/xlsx/xform/sheet/dimension-xform' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/xlsx/xform/sheet/drawing-xform' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/xlsx/xform/sheet/hyperlink-xform' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/xlsx/xform/sheet/merge-cell-xform' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/xlsx/xform/sheet/merges' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/xlsx/xform/sheet/outline-properties-xform' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/xlsx/xform/sheet/page-breaks-xform' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/xlsx/xform/sheet/page-margins-xform' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/xlsx/xform/sheet/page-setup-properties-xform' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/xlsx/xform/sheet/page-setup-xform' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/xlsx/xform/sheet/picture-xform' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/xlsx/xform/sheet/print-options-xform' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/xlsx/xform/sheet/row-breaks-xform' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/xlsx/xform/sheet/row-xform' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/xlsx/xform/sheet/sheet-format-properties-xform' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/xlsx/xform/sheet/sheet-properties-xform' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/xlsx/xform/sheet/sheet-view-xform' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/xlsx/xform/sheet/worksheet-xform' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/xlsx/xform/simple/boolean-xform' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/xlsx/xform/simple/date-xform' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/xlsx/xform/simple/float-xform' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/xlsx/xform/simple/integer-xform' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/xlsx/xform/simple/string-xform' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/xlsx/xform/static-xform' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/xlsx/xform/strings/phonetic-text-xform' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/xlsx/xform/strings/rich-text-xform' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/xlsx/xform/strings/shared-string-xform' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/xlsx/xform/strings/shared-strings-xform' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/xlsx/xform/strings/text-xform' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/xlsx/xform/style/alignment-xform' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/xlsx/xform/style/border-xform' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/xlsx/xform/style/color-xform' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/xlsx/xform/style/fill-xform' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/xlsx/xform/style/font-xform' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/xlsx/xform/style/numfmt-xform' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/xlsx/xform/style/style-xform' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/xlsx/xform/style/styles-xform' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/xlsx/xform/style/underline-xform' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/xlsx/xlsx' {
  declare module.exports: any;
}

declare module 'exceljs/dist/es5/xlsx/xml/theme1' {
  declare module.exports: any;
}

declare module 'exceljs/dist/exceljs' {
  declare module.exports: any;
}

declare module 'exceljs/dist/exceljs.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'exceljs/dist/es5/config/set-value.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/config/set-value'>;
}
declare module 'exceljs/dist/es5/csv/csv.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/csv/csv'>;
}
declare module 'exceljs/dist/es5/csv/line-buffer.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/csv/line-buffer'>;
}
declare module 'exceljs/dist/es5/csv/stream-converter.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/csv/stream-converter'>;
}
declare module 'exceljs/dist/es5/doc/cell.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/doc/cell'>;
}
declare module 'exceljs/dist/es5/doc/column.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/doc/column'>;
}
declare module 'exceljs/dist/es5/doc/data-validations.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/doc/data-validations'>;
}
declare module 'exceljs/dist/es5/doc/defined-names.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/doc/defined-names'>;
}
declare module 'exceljs/dist/es5/doc/enums.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/doc/enums'>;
}
declare module 'exceljs/dist/es5/doc/modelcontainer.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/doc/modelcontainer'>;
}
declare module 'exceljs/dist/es5/doc/range.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/doc/range'>;
}
declare module 'exceljs/dist/es5/doc/row.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/doc/row'>;
}
declare module 'exceljs/dist/es5/doc/workbook.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/doc/workbook'>;
}
declare module 'exceljs/dist/es5/doc/worksheet.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/doc/worksheet'>;
}
declare module 'exceljs/dist/es5/exceljs.browser.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/exceljs.browser'>;
}
declare module 'exceljs/dist/es5/exceljs.nodejs.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/exceljs.nodejs'>;
}
declare module 'exceljs/dist/es5/index.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/index'>;
}
declare module 'exceljs/dist/es5/stream/xlsx/hyperlink-reader.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/stream/xlsx/hyperlink-reader'>;
}
declare module 'exceljs/dist/es5/stream/xlsx/sheet-rels-writer.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/stream/xlsx/sheet-rels-writer'>;
}
declare module 'exceljs/dist/es5/stream/xlsx/workbook-reader.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/stream/xlsx/workbook-reader'>;
}
declare module 'exceljs/dist/es5/stream/xlsx/workbook-writer.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/stream/xlsx/workbook-writer'>;
}
declare module 'exceljs/dist/es5/stream/xlsx/worksheet-reader.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/stream/xlsx/worksheet-reader'>;
}
declare module 'exceljs/dist/es5/stream/xlsx/worksheet-writer.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/stream/xlsx/worksheet-writer'>;
}
declare module 'exceljs/dist/es5/utils/auto-drain.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/utils/auto-drain'>;
}
declare module 'exceljs/dist/es5/utils/cell-matrix.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/utils/cell-matrix'>;
}
declare module 'exceljs/dist/es5/utils/col-cache.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/utils/col-cache'>;
}
declare module 'exceljs/dist/es5/utils/flow-control.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/utils/flow-control'>;
}
declare module 'exceljs/dist/es5/utils/promish.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/utils/promish'>;
}
declare module 'exceljs/dist/es5/utils/shared-formula.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/utils/shared-formula'>;
}
declare module 'exceljs/dist/es5/utils/shared-strings.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/utils/shared-strings'>;
}
declare module 'exceljs/dist/es5/utils/stream-base64.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/utils/stream-base64'>;
}
declare module 'exceljs/dist/es5/utils/stream-buf.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/utils/stream-buf'>;
}
declare module 'exceljs/dist/es5/utils/string-buf.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/utils/string-buf'>;
}
declare module 'exceljs/dist/es5/utils/string-builder.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/utils/string-builder'>;
}
declare module 'exceljs/dist/es5/utils/stuttered-pipe.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/utils/stuttered-pipe'>;
}
declare module 'exceljs/dist/es5/utils/typed-stack.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/utils/typed-stack'>;
}
declare module 'exceljs/dist/es5/utils/under-dash.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/utils/under-dash'>;
}
declare module 'exceljs/dist/es5/utils/utils.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/utils/utils'>;
}
declare module 'exceljs/dist/es5/utils/xml-stream.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/utils/xml-stream'>;
}
declare module 'exceljs/dist/es5/utils/zip-stream.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/utils/zip-stream'>;
}
declare module 'exceljs/dist/es5/xlsx/defaultnumformats.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/xlsx/defaultnumformats'>;
}
declare module 'exceljs/dist/es5/xlsx/rel-type.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/xlsx/rel-type'>;
}
declare module 'exceljs/dist/es5/xlsx/xform/base-xform.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/xlsx/xform/base-xform'>;
}
declare module 'exceljs/dist/es5/xlsx/xform/book/defined-name-xform.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/xlsx/xform/book/defined-name-xform'>;
}
declare module 'exceljs/dist/es5/xlsx/xform/book/sheet-xform.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/xlsx/xform/book/sheet-xform'>;
}
declare module 'exceljs/dist/es5/xlsx/xform/book/workbook-properties-xform.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/xlsx/xform/book/workbook-properties-xform'>;
}
declare module 'exceljs/dist/es5/xlsx/xform/book/workbook-view-xform.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/xlsx/xform/book/workbook-view-xform'>;
}
declare module 'exceljs/dist/es5/xlsx/xform/book/workbook-xform.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/xlsx/xform/book/workbook-xform'>;
}
declare module 'exceljs/dist/es5/xlsx/xform/composite-xform.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/xlsx/xform/composite-xform'>;
}
declare module 'exceljs/dist/es5/xlsx/xform/core/app-heading-pairs-xform.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/xlsx/xform/core/app-heading-pairs-xform'>;
}
declare module 'exceljs/dist/es5/xlsx/xform/core/app-titles-of-parts-xform.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/xlsx/xform/core/app-titles-of-parts-xform'>;
}
declare module 'exceljs/dist/es5/xlsx/xform/core/app-xform.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/xlsx/xform/core/app-xform'>;
}
declare module 'exceljs/dist/es5/xlsx/xform/core/content-types-xform.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/xlsx/xform/core/content-types-xform'>;
}
declare module 'exceljs/dist/es5/xlsx/xform/core/core-xform.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/xlsx/xform/core/core-xform'>;
}
declare module 'exceljs/dist/es5/xlsx/xform/core/relationship-xform.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/xlsx/xform/core/relationship-xform'>;
}
declare module 'exceljs/dist/es5/xlsx/xform/core/relationships-xform.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/xlsx/xform/core/relationships-xform'>;
}
declare module 'exceljs/dist/es5/xlsx/xform/drawing/blip-fill-xform.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/xlsx/xform/drawing/blip-fill-xform'>;
}
declare module 'exceljs/dist/es5/xlsx/xform/drawing/blip-xform.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/xlsx/xform/drawing/blip-xform'>;
}
declare module 'exceljs/dist/es5/xlsx/xform/drawing/cell-position-xform.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/xlsx/xform/drawing/cell-position-xform'>;
}
declare module 'exceljs/dist/es5/xlsx/xform/drawing/drawing-xform.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/xlsx/xform/drawing/drawing-xform'>;
}
declare module 'exceljs/dist/es5/xlsx/xform/drawing/nv-pic-pr-xform.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/xlsx/xform/drawing/nv-pic-pr-xform'>;
}
declare module 'exceljs/dist/es5/xlsx/xform/drawing/pic-xform.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/xlsx/xform/drawing/pic-xform'>;
}
declare module 'exceljs/dist/es5/xlsx/xform/drawing/sp-pr.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/xlsx/xform/drawing/sp-pr'>;
}
declare module 'exceljs/dist/es5/xlsx/xform/drawing/two-cell-anchor-xform.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/xlsx/xform/drawing/two-cell-anchor-xform'>;
}
declare module 'exceljs/dist/es5/xlsx/xform/list-xform.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/xlsx/xform/list-xform'>;
}
declare module 'exceljs/dist/es5/xlsx/xform/sheet/auto-filter-xform.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/xlsx/xform/sheet/auto-filter-xform'>;
}
declare module 'exceljs/dist/es5/xlsx/xform/sheet/cell-xform.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/xlsx/xform/sheet/cell-xform'>;
}
declare module 'exceljs/dist/es5/xlsx/xform/sheet/col-xform.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/xlsx/xform/sheet/col-xform'>;
}
declare module 'exceljs/dist/es5/xlsx/xform/sheet/data-validations-xform.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/xlsx/xform/sheet/data-validations-xform'>;
}
declare module 'exceljs/dist/es5/xlsx/xform/sheet/dimension-xform.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/xlsx/xform/sheet/dimension-xform'>;
}
declare module 'exceljs/dist/es5/xlsx/xform/sheet/drawing-xform.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/xlsx/xform/sheet/drawing-xform'>;
}
declare module 'exceljs/dist/es5/xlsx/xform/sheet/hyperlink-xform.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/xlsx/xform/sheet/hyperlink-xform'>;
}
declare module 'exceljs/dist/es5/xlsx/xform/sheet/merge-cell-xform.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/xlsx/xform/sheet/merge-cell-xform'>;
}
declare module 'exceljs/dist/es5/xlsx/xform/sheet/merges.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/xlsx/xform/sheet/merges'>;
}
declare module 'exceljs/dist/es5/xlsx/xform/sheet/outline-properties-xform.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/xlsx/xform/sheet/outline-properties-xform'>;
}
declare module 'exceljs/dist/es5/xlsx/xform/sheet/page-breaks-xform.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/xlsx/xform/sheet/page-breaks-xform'>;
}
declare module 'exceljs/dist/es5/xlsx/xform/sheet/page-margins-xform.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/xlsx/xform/sheet/page-margins-xform'>;
}
declare module 'exceljs/dist/es5/xlsx/xform/sheet/page-setup-properties-xform.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/xlsx/xform/sheet/page-setup-properties-xform'>;
}
declare module 'exceljs/dist/es5/xlsx/xform/sheet/page-setup-xform.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/xlsx/xform/sheet/page-setup-xform'>;
}
declare module 'exceljs/dist/es5/xlsx/xform/sheet/picture-xform.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/xlsx/xform/sheet/picture-xform'>;
}
declare module 'exceljs/dist/es5/xlsx/xform/sheet/print-options-xform.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/xlsx/xform/sheet/print-options-xform'>;
}
declare module 'exceljs/dist/es5/xlsx/xform/sheet/row-breaks-xform.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/xlsx/xform/sheet/row-breaks-xform'>;
}
declare module 'exceljs/dist/es5/xlsx/xform/sheet/row-xform.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/xlsx/xform/sheet/row-xform'>;
}
declare module 'exceljs/dist/es5/xlsx/xform/sheet/sheet-format-properties-xform.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/xlsx/xform/sheet/sheet-format-properties-xform'>;
}
declare module 'exceljs/dist/es5/xlsx/xform/sheet/sheet-properties-xform.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/xlsx/xform/sheet/sheet-properties-xform'>;
}
declare module 'exceljs/dist/es5/xlsx/xform/sheet/sheet-view-xform.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/xlsx/xform/sheet/sheet-view-xform'>;
}
declare module 'exceljs/dist/es5/xlsx/xform/sheet/worksheet-xform.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/xlsx/xform/sheet/worksheet-xform'>;
}
declare module 'exceljs/dist/es5/xlsx/xform/simple/boolean-xform.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/xlsx/xform/simple/boolean-xform'>;
}
declare module 'exceljs/dist/es5/xlsx/xform/simple/date-xform.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/xlsx/xform/simple/date-xform'>;
}
declare module 'exceljs/dist/es5/xlsx/xform/simple/float-xform.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/xlsx/xform/simple/float-xform'>;
}
declare module 'exceljs/dist/es5/xlsx/xform/simple/integer-xform.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/xlsx/xform/simple/integer-xform'>;
}
declare module 'exceljs/dist/es5/xlsx/xform/simple/string-xform.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/xlsx/xform/simple/string-xform'>;
}
declare module 'exceljs/dist/es5/xlsx/xform/static-xform.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/xlsx/xform/static-xform'>;
}
declare module 'exceljs/dist/es5/xlsx/xform/strings/phonetic-text-xform.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/xlsx/xform/strings/phonetic-text-xform'>;
}
declare module 'exceljs/dist/es5/xlsx/xform/strings/rich-text-xform.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/xlsx/xform/strings/rich-text-xform'>;
}
declare module 'exceljs/dist/es5/xlsx/xform/strings/shared-string-xform.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/xlsx/xform/strings/shared-string-xform'>;
}
declare module 'exceljs/dist/es5/xlsx/xform/strings/shared-strings-xform.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/xlsx/xform/strings/shared-strings-xform'>;
}
declare module 'exceljs/dist/es5/xlsx/xform/strings/text-xform.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/xlsx/xform/strings/text-xform'>;
}
declare module 'exceljs/dist/es5/xlsx/xform/style/alignment-xform.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/xlsx/xform/style/alignment-xform'>;
}
declare module 'exceljs/dist/es5/xlsx/xform/style/border-xform.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/xlsx/xform/style/border-xform'>;
}
declare module 'exceljs/dist/es5/xlsx/xform/style/color-xform.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/xlsx/xform/style/color-xform'>;
}
declare module 'exceljs/dist/es5/xlsx/xform/style/fill-xform.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/xlsx/xform/style/fill-xform'>;
}
declare module 'exceljs/dist/es5/xlsx/xform/style/font-xform.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/xlsx/xform/style/font-xform'>;
}
declare module 'exceljs/dist/es5/xlsx/xform/style/numfmt-xform.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/xlsx/xform/style/numfmt-xform'>;
}
declare module 'exceljs/dist/es5/xlsx/xform/style/style-xform.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/xlsx/xform/style/style-xform'>;
}
declare module 'exceljs/dist/es5/xlsx/xform/style/styles-xform.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/xlsx/xform/style/styles-xform'>;
}
declare module 'exceljs/dist/es5/xlsx/xform/style/underline-xform.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/xlsx/xform/style/underline-xform'>;
}
declare module 'exceljs/dist/es5/xlsx/xlsx.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/xlsx/xlsx'>;
}
declare module 'exceljs/dist/es5/xlsx/xml/theme1.js' {
  declare module.exports: $Exports<'exceljs/dist/es5/xlsx/xml/theme1'>;
}
declare module 'exceljs/dist/exceljs.js' {
  declare module.exports: $Exports<'exceljs/dist/exceljs'>;
}
declare module 'exceljs/dist/exceljs.min.js' {
  declare module.exports: $Exports<'exceljs/dist/exceljs.min'>;
}
