// flow-typed signature: d994553dab597a2c2f10106a4e3eb076
// flow-typed version: <<STUB>>/mst-middlewares_v3.2.4/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mst-middlewares'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mst-middlewares' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mst-middlewares/dist/mst-middlewares' {
  declare module.exports: any;
}

declare module 'mst-middlewares/dist/mst-middlewares.module' {
  declare module.exports: any;
}

declare module 'mst-middlewares/dist/mst-middlewares.umd' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mst-middlewares/dist/mst-middlewares.js' {
  declare module.exports: $Exports<'mst-middlewares/dist/mst-middlewares'>;
}
declare module 'mst-middlewares/dist/mst-middlewares.module.js' {
  declare module.exports: $Exports<'mst-middlewares/dist/mst-middlewares.module'>;
}
declare module 'mst-middlewares/dist/mst-middlewares.umd.js' {
  declare module.exports: $Exports<'mst-middlewares/dist/mst-middlewares.umd'>;
}
