// flow-typed signature: 22b52b3e69c130401e402e2a616bfc3f
// flow-typed version: <<STUB>>/react-reflex_v2.2.9/flow_v0.82.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-reflex'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-reflex' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-reflex/dist/commonjs/Browser' {
  declare module.exports: any;
}

declare module 'react-reflex/dist/commonjs/index' {
  declare module.exports: any;
}

declare module 'react-reflex/dist/commonjs/ReflexContainer' {
  declare module.exports: any;
}

declare module 'react-reflex/dist/commonjs/ReflexElement' {
  declare module.exports: any;
}

declare module 'react-reflex/dist/commonjs/ReflexEvents' {
  declare module.exports: any;
}

declare module 'react-reflex/dist/commonjs/ReflexHandle' {
  declare module.exports: any;
}

declare module 'react-reflex/dist/commonjs/ReflexSplitter' {
  declare module.exports: any;
}

declare module 'react-reflex/dist/demo/bundle' {
  declare module.exports: any;
}

declare module 'react-reflex/dist/es/Browser' {
  declare module.exports: any;
}

declare module 'react-reflex/dist/es/index' {
  declare module.exports: any;
}

declare module 'react-reflex/dist/es/ReflexContainer' {
  declare module.exports: any;
}

declare module 'react-reflex/dist/es/ReflexElement' {
  declare module.exports: any;
}

declare module 'react-reflex/dist/es/ReflexEvents' {
  declare module.exports: any;
}

declare module 'react-reflex/dist/es/ReflexHandle' {
  declare module.exports: any;
}

declare module 'react-reflex/dist/es/ReflexSplitter' {
  declare module.exports: any;
}

declare module 'react-reflex/dist/umd/react-reflex' {
  declare module.exports: any;
}

declare module 'react-reflex/dist/umd/react-reflex.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-reflex/dist/commonjs/Browser.js' {
  declare module.exports: $Exports<'react-reflex/dist/commonjs/Browser'>;
}
declare module 'react-reflex/dist/commonjs/index.js' {
  declare module.exports: $Exports<'react-reflex/dist/commonjs/index'>;
}
declare module 'react-reflex/dist/commonjs/ReflexContainer.js' {
  declare module.exports: $Exports<'react-reflex/dist/commonjs/ReflexContainer'>;
}
declare module 'react-reflex/dist/commonjs/ReflexElement.js' {
  declare module.exports: $Exports<'react-reflex/dist/commonjs/ReflexElement'>;
}
declare module 'react-reflex/dist/commonjs/ReflexEvents.js' {
  declare module.exports: $Exports<'react-reflex/dist/commonjs/ReflexEvents'>;
}
declare module 'react-reflex/dist/commonjs/ReflexHandle.js' {
  declare module.exports: $Exports<'react-reflex/dist/commonjs/ReflexHandle'>;
}
declare module 'react-reflex/dist/commonjs/ReflexSplitter.js' {
  declare module.exports: $Exports<'react-reflex/dist/commonjs/ReflexSplitter'>;
}
declare module 'react-reflex/dist/demo/bundle.js' {
  declare module.exports: $Exports<'react-reflex/dist/demo/bundle'>;
}
declare module 'react-reflex/dist/es/Browser.js' {
  declare module.exports: $Exports<'react-reflex/dist/es/Browser'>;
}
declare module 'react-reflex/dist/es/index.js' {
  declare module.exports: $Exports<'react-reflex/dist/es/index'>;
}
declare module 'react-reflex/dist/es/ReflexContainer.js' {
  declare module.exports: $Exports<'react-reflex/dist/es/ReflexContainer'>;
}
declare module 'react-reflex/dist/es/ReflexElement.js' {
  declare module.exports: $Exports<'react-reflex/dist/es/ReflexElement'>;
}
declare module 'react-reflex/dist/es/ReflexEvents.js' {
  declare module.exports: $Exports<'react-reflex/dist/es/ReflexEvents'>;
}
declare module 'react-reflex/dist/es/ReflexHandle.js' {
  declare module.exports: $Exports<'react-reflex/dist/es/ReflexHandle'>;
}
declare module 'react-reflex/dist/es/ReflexSplitter.js' {
  declare module.exports: $Exports<'react-reflex/dist/es/ReflexSplitter'>;
}
declare module 'react-reflex/dist/umd/react-reflex.js' {
  declare module.exports: $Exports<'react-reflex/dist/umd/react-reflex'>;
}
declare module 'react-reflex/dist/umd/react-reflex.min.js' {
  declare module.exports: $Exports<'react-reflex/dist/umd/react-reflex.min'>;
}
