// flow-typed signature: 4e9a02c8a22d68f77d51a8736d650a7b
// flow-typed version: <<STUB>>/username_v4.1.0/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'username'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'username' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'username/index' {
  declare module.exports: $Exports<'username'>;
}
declare module 'username/index.js' {
  declare module.exports: $Exports<'username'>;
}
