// flow-typed signature: cb52209103adb340e3831a96751483dd
// flow-typed version: <<STUB>>/@hocs/with-lifecycle_v0.5.0/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@hocs/with-lifecycle'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@hocs/with-lifecycle' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@hocs/with-lifecycle/build/browser-esm/index' {
  declare module.exports: any;
}

declare module '@hocs/with-lifecycle/build/node-cjs/index' {
  declare module.exports: any;
}

declare module '@hocs/with-lifecycle/build/react-native/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@hocs/with-lifecycle/build/browser-esm/index.js' {
  declare module.exports: $Exports<'@hocs/with-lifecycle/build/browser-esm/index'>;
}
declare module '@hocs/with-lifecycle/build/node-cjs/index.js' {
  declare module.exports: $Exports<'@hocs/with-lifecycle/build/node-cjs/index'>;
}
declare module '@hocs/with-lifecycle/build/react-native/index.js' {
  declare module.exports: $Exports<'@hocs/with-lifecycle/build/react-native/index'>;
}
